### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by jordanmaguire**
See README for info

### CODE REVIEW

**Comment by pzi** [comment]
Would it make sense to make 1 gem for all our customisations/extensions like selectize and datepicker? Or do you prefer to have a gem each?

**Comment by BenR1312** [comment]
This was pretty cool to look over, spoke with jordan directly about a few peices of it and it seems all good.
it will be interesting to see how it goes in practice

**Comment by psyren89** [comment]
@pzi modular is best. That way, we only need to pull in the things we need. Naturally, we could create a mega-gem afterwards.

**Comment by jordanmaguire** [comment]
ya boy @psyren89 is correct.

**Pull request merged**
